# Setup
title:               Gracefully Evan
tagline:             'Bits, bytes and beyond'
description:         'Welcome, this is a space where I share insights and tutorials on web development and data analytics.'
url:                 //evangelistagrace.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Evangelista Grace
  url:               https://evangelistagrace.github.io
  email:             grace.evangrace@gmail.com

# Gems
plugins: 
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
